Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -27,16 +27,16 @@ jobs:
           destination: jmeter-report
       - run:
          name: Fail Build on High Response Times
-    command: |
-      if [ -f report/statistics.json ]; then
-        avg_time=$(grep -oP '(?<=<average>).*(?=</average>)' report/statistics.json)
-        if [ "$avg_time" -gt 2000 ]; then
-          echo "Average response time is too high: $avg_time ms"
-          exit 1
-        fi
-      else
-        echo "Warning: statistics.json not found. Skipping performance check."
-      fi
+          command: |
+            if [ -f report/statistics.json ]; then
+              avg_time=$(grep -oP '(?<=<average>).*(?=</average>)' report/statistics.json)
+              if [ "$avg_time" -gt 2000 ]; then
+                echo "Average response time is too high: $avg_time ms"
+                exit 1
+              fi
+            else
+              echo "Warning: statistics.json not found. Skipping performance check."
+            fi
 
 workflows:
   version: 2
